# site settings
title: SOLARPUNK TRAVEL COOPERATIVE
subtitle:
email: thecooptrail@gmail.com
description: 'regenerative travel community'
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone:
discord: https://discord.gg/6VbCwAcHwg
hylo: https://www.hylo.com/groups/coop-trail

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
facebook_url: https://www.facebook.com/solarpunk_travel
instagram_url: https://www.instagram.com/solarpunk_travel/
linkedin_url: https://www.linkedin.com/company/solarpunk_travel
slack_url:
twitter_url: https://twitter.com/solarpunk_travel
youtube_url: https://www.youtube.com/channel/UCjcZqjYIyFCo9SC0YaBy6Mg
tiktok_url: https://www.tiktok.com/@solarpunk_travel

# build settings
markdown: kramdown

sass:
  style: compressed
